# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  #config.vm.box = "geerlingguy/ubuntu1604"
  config.ssh.insert_key = false
  # prevent vagrant from mounting the default /vagrant synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 256
    #v.memory = 1024
    v.linked_clone = true
  end

  # Application server 1
  config.vm.define "app1" do |app|
    app.vm.hostname = "app1.test"
    app.vm.network :private_network, ip: "192.168.60.4"
  end

  # Application server 2
  config.vm.define "app2" do |app|
    app.vm.hostname = "app2.test"
    app.vm.network :private_network, ip: "192.168.60.5"
  end

  # Database server
  config.vm.define "db" do |db|
    db.vm.hostname = "db.test"
    db.vm.network :private_network, ip: "192.168.60.6"
  end
end
