---
- hosts: all
  become: yes

  vars:
    node_apps_location: /opt/nodejs

  roles:
    - { role: yum-repo-setup, yum_repo_name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm", rpm_key: "http://rpms.remirepo.net/RPM-GPG-KEY-remi" }
    - { role: yum-repo-setup, yum_repo_name: epel-release}
    - firewall
    - nodejs
    - app-deploy