---
- name: Ensure Node.js app folder exists
  file: "path={{ node_apps_location }} state=directory"

- name: Copy example Node.js app to server
  copy: "src=/opt/ansible/examples/nodejs-app/files/ dest={{ node_apps_location }}/nodejs-app"

- name: Install app dependencies defined in package.json
  npm: path={{ node_apps_location }}/nodejs-app

- name: Check list of running Node.js apps
  command: forever list
  register: forever_list
  changed_when: false

- name: Start example Node.js app
  command: "forever start {{ node_apps_location }}/nodejs-app/app.js"
  when: "forever_list.stdout.find(node_apps_location + '/nodejs-app/app.js') == -1"